workspace = { members = [ "members/enum-example-01","members/enums"] }
[package]
name = "ch05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
